apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
  labels:
    name: fleetman-webapp
spec:
  selector:
    name: webapp
  
  ports:
    - port: 80
      nodePort: 30080
      name: http
  
  type: NodePort